spring:
  application:
    name: chat
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/im?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 18080

mybatis:
  type-aliases-package: com.yuan.domain
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    cn.itech4u: INFO